stages:
  - linting

linting:
  stage: linting
  image: condaforge/mambaforge:22.9.0-2
  script:
    - pip install git+https://github.com/psf/black
    - pip install isort
    - pip install flake8
    - black --check buzzard buzzard.py --line-length 120
    - isort buzzard buzzard.py --check-only --profile black
    - flake8 buzzard buzzard.py --max-line-length 120
