name: linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose -l 120"
          src: "./buzzard, buzzard.py"
      - uses: actions/checkout@v2
      - uses: PyCQA/isort@5.10.1
        with:
          options: "--check-only"
          src: "./buzzard, buzzard.py"
      - uses: actions/checkout@v2
      - uses: PyCQA/flake8@5.0.4
        with:
          options: "--max-line-length 120"
          src: "./buzzard, buzzard.py"
