name: linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install black, isort and flake8
        run: pip install black isort flake8
      - name: run black, isort and flake8
        run: |
         black ./buzzard buzzard.py --check --verbose --line-length 120 
         isort ./buzzard buzzard.py --check-only --verbose --profile black
         flake8 ./buzzard buzzard.py --max-line-length 120 --verbose
         
