name: Run tests

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env

      - name: Install Eigen
        shell: bash -l {0}
        run: |
          git clone --branch 3.4.0 https://gitlab.com/libeigen/eigen.git
          cd eigen 
          mkdir build
          cd build 
          cmake -DBUILD_TESTING=OFF  -DINCLUDE_INSTALL_DIR=$CONDA_PREFIX/include -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..
          make install
          cd ../..

      - name: Install Autodiff
        shell: bash -l {0}
        run: |
          git clone --branch v1.1.0 https://github.com/autodiff/autodiff.git
          cd autodiff
          mkdir build
          cd build
          cmake -DAUTODIFF_BUILD_TESTS=OFF \
            -DAUTODIFF_BUILD_PYTHON=OFF \
            -DAUTODIFF_BUILD_EXAMPLES=OFF \
            -DAUTODIFF_BUILD_DOCS=OFF \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            ..
          make install
          cd ../..

      - name: Install Marmot
        shell: bash -l {0}
        run: |
          git clone --recurse-submodules https://github.com/MAteRialMOdelingToolbox/Marmot/
          cd Marmot
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..
          make install
          cd ../..

      - name: Build EdelweissFE
        shell: bash -l {0}
        run: |
          git clone https://github.com/EdelweissFE/EdelweissFE.git
          cd EdelweissFE
          mamba install --file requirements.txt
          pip install .
          cd ..

      - name: Run Buzzard tests
        shell: bash -l {0}
        run: |
          python -m pip install -r requirements.txt
          python run_edelweiss_tests.py
